---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=karaf-fuse-73&var-version=1.0-SNAPSHOT
  labels:
    app: karaf-fuse-73
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: org.example.fis
  name: karaf-fuse-73
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: karaf-fuse-73
    provider: fabric8
    group: org.example.fis
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: img/icons/camel.svg
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=karaf-fuse-73&var-version=1.0-SNAPSHOT
      labels:
        app: karaf-fuse-73
        provider: fabric8
        version: 1.0-SNAPSHOT
        group: org.example.fis
    spec:
      containers:
      - env:
        - name: QUICKSTART_NAME
          value: karaf-camel-log
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: karaf-fuse-73:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8181
          initialDelaySeconds: 180
        name: karaf
        ports:
        - containerPort: 8181
          name: intermapper
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readiness-check
            port: 8181
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 128Mi
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - karaf
      from:
        kind: ImageStreamTag
        name: karaf-fuse-73:latest
    type: ImageChange
