---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/camel.svg
  labels:
    app: karaf-fuse-73
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: org.example.fis
  name: karaf-fuse-73
spec:
  ports:
  - name: intermapper
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: karaf-fuse-73
    provider: fabric8
    group: org.example.fis
